spring:
  application:
    name: server
  profiles:
    default: local

server:
  servlet:
    context-path: /server

# OAuth2
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    app-key: ${OAUTH_KAKAO_APP_KEY}
    public-key-url: /.well-known/jwks.json

# JWT
jwt:
  header: Authorization
  type: Bearer
  issuer: ${ISSUER_NAME}
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

# Observability Tools Basic Auth
observability:
  prometheus:
    username: ${PROMETHEUS_USERNAME}
    password: ${PROMETHEUS_PASSWORD}
