spring:
  config:
    import:
    - optional:file:beforegoing-server/.env[.properties]

# JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

# RDB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: h2test
    password: h2test

# Redis
  data:
    redis:
      host: localhost
      port: 6379

# Sentry
sentry:
  enabled: false

# Springdoc (Swagger)
springdoc:
  server:
    url: http://localhost:8080/server
    description: Local Server

# Actuator
management:
  server:
    port: 10090
  endpoints:
    web:
      base-path: /server/actuator
      exposure:
        include: "*"
