spring:

# JPA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

# RDB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_DATASOURCE_ENDPOINT}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    hikari:
      max-lifetime: 1190000

# Redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

# Sentry
sentry:
  dsn: ${SENTRY_DSN}
  environment: prod
  send-default-pii: false
  traces-sample-rate: 0.2
  exception-resolver-order: -2147483647
  max-request-body-size: medium

# Springdoc (Swagger)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Actuator
management:
  server:
    port: 10090
  endpoints:
    web:
      base-path: /server/actuator
      exposure:
        include: health, prometheus
