spring:
  application:
    name: server
  profiles:
    default: local

server:
  servlet:
    context-path: /server

# OAuth2
oauth:
  kakao:
    base-url: https://kauth.kakao.com
    public-key-url: /.well-known/jwks.json
    app-key: ${OAUTH_KAKAO_APP_KEY}
  apple:
    base-url: https://appleid.apple.com
    public-key-url: /auth/keys
    app-id: ${OAUTH_APPLE_APP_ID}

# JWT
jwt:
  header: Authorization
  type: Bearer
  issuer: ${ISSUER_NAME}
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

# Observability Tools Basic Auth
observability:
  prometheus:
    username: ${PROMETHEUS_USERNAME}
    password: ${PROMETHEUS_PASSWORD}

# Weather APIs
weather:
  kma:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    service-key: ${KMA_SERVICE_KEY}
  open-meteo:
    base-url: https://air-quality-api.open-meteo.com/v1
